<?php
session_start();
if($_SESSION['userid']==""){
   header("Location:../sessionExpire.php");
   exit;
}
ob_start(); 
require_once("dbconnect.php");
require_once("../includes/globalvariables.php");
require_once("../includes/common_function.php");
?>
